version: '3.1'

services:

  wordpress.test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        wp_docker_tag: '$WP_DOCKER_TAG'
        XDEBUG_VERSION: '$XDEBUG_VERSION'
    restart: always
    ports:
      - 80:80
    environment:
      - APACHE_RUN_USER="#33"
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
      - WORDPRESS_DEBUG=1
      - XDEBUG_MODE=coverage
      - WP_ROOT_FOLDER
      - WORDPRESS_CONFIG_EXTRA=define('WP_AUTO_UPDATE_CORE', false);
      - TEST_SITE_WP_ADMIN_PATH
      - TEST_SITE_DB_NAME
      - TEST_SITE_DB_HOST
      - TEST_SITE_DB_USER
      - TEST_SITE_DB_PASSWORD
      - TEST_SITE_TABLE_PREFIX
      - TEST_SITE_WP_URL
      - TEST_SITE_WP_DOMAIN
      - TEST_SITE_ADMIN_EMAIL
      - TEST_SITE_ADMIN_USERNAME
      - TEST_SITE_ADMIN_PASSWORD
    volumes:
      - wordpress:/var/www/html
      # - ./wp-content:/var/www/html/wp-content
      - ./:/var/www/html/wp-content/plugins/disable-media-pages

  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      CHROMEDRIVER_EXTRA_ARGS: "--verbose"
    volumes:
      - db:/var/lib/mysql
  chromedriver:
    image: seleniarm/standalone-chromium
    expose:
      - "4444"
    privileged: true
    shm_size: 2G

volumes:
  wordpress:
  db:
